### ISSUE TITLE
Justificativa

### ISSUE THREAD

**Issue by laura-lannab** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t5-quem-paga-quanto#4]

**Comment by ldenardin** [comment]
Dúvida: pode usar os dados de 2017 a 2020?

**Comment by laura-lannab** [comment]
- [ ] Normas ABNT
- [x] Adicionar as referências

**Comment by figueiredobarbara** [comment]
- [ ] Remover uma das personas (Gisele) e alterar a persona 'Enzo' para a mãe dele;
- [ ] Adicionar nome às historias de usuario.
- [ ] Formatar as personas para tabela 
- [ ] Pensar em boas praticas para RNF
