### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by laura-lannab** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t5-quem-paga-quanto#7]

**Comment by cj-2** [comment]
Gente acredito que podemos adicionar essa persona com a história de usuário:

Roberto é um rapaz de 26 anos, trabalha como desenvolvedor e mora com sua namorada que irá começar a contribuir nas contas de casa, pois acabou de formar e começou a trabalhar.

Roberto quer dividir as contas de forma justa já que no passado ao tentar dividir as contas com sua namorada não sobrava nada para a mesma. Por isso, agora ele está procurando uma ferramenta para calcular quando cada um deve contribuir de uma forma que sobre dinheiro para ambos.

**Comment by laura-lannab** [comment]
- [x] Retirar a persona Gisela, e trocar por um administrador(dono) de república
- [x] Alterar a persona Enzo pela mãe
- [x] Formatar as personas, colocar foto e usar uma tabela
